### ISSUE TITLE
Wrong output formatting in _formatDecimal ind IINvoiceDescriptorWriter.cs

### ISSUE THREAD

**Issue by goedo** [stephanstapel/ZUGFeRD-csharp#267]
Output wrong for XML file happens if more than 3 digits. Furthermore, not round:

![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/ac32366d-f009-423c-b3b1-ba70713cce96)
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/38a23a7f-7e14-48fe-8539-07376f8e31fa)
so
            //return Math.Round(value, numDecimals).ToString($"N{numDecimals}", CultureInfo.InvariantCulture);
            return Math.Round(value, numDecimals, MidpointRounding.AwayFromZero).ToString(); //roger

TBD: check if the rounding is useful

**Comment by stephanstapel** [comment]
I fixed this bug yesterday. Please fetch the new version!

**Comment by goedo** [comment]
Yeah I JUST saw this! :-)
But you are still not rounding, only cutting - is that ok?

**Comment by stephanstapel** [comment]
It should do rounding correctly:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/cd32e43b-7854-47f8-8811-5dfa40fe3750)

**Comment by goedo** [comment]
great, verified. Seems awayfromzero is a default... but keep in mind that .net changes default (like the UTF as default coding in .net core). So it will be useful have that in mind if in some later version the rounding changes.
Can close this, of course, thanks.
